// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(WalletKitFFI)
import WalletKitFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_walletkit_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_walletkit_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureWalletkitInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol AlloyClientProtocol: AnyObject, Sendable {
    
    func address()  -> String
    
    func chainId()  -> UInt64
    
    func derivationPath()  -> String?
    
    func isActiveAddress(address: String)  -> Bool
    
    func isValidAddress(address: String)  -> Bool
    
}
open class AlloyClient: AlloyClientProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_walletkit_fn_clone_alloyclient(self.handle, $0) }
    }
public convenience init(chainId: UInt64, accountIndex: UInt64, privateKey: [UInt8], password: String?)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_walletkit_fn_constructor_alloyclient_new(
        FfiConverterUInt64.lower(chainId),
        FfiConverterUInt64.lower(accountIndex),
        FfiConverterSequenceUInt8.lower(privateKey),
        FfiConverterOptionString.lower(password),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_walletkit_fn_free_alloyclient(handle, $0) }
    }

    
public static func newTrezor(chainId: UInt64, accountIndex: UInt64, deviceId: String)async throws  -> AlloyClient  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_constructor_alloyclient_new_trezor(FfiConverterUInt64.lower(chainId),FfiConverterUInt64.lower(accountIndex),FfiConverterString.lower(deviceId)
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_u64,
            completeFunc: ffi_walletkit_rust_future_complete_u64,
            freeFunc: ffi_walletkit_rust_future_free_u64,
            liftFunc: FfiConverterTypeAlloyClient_lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    
public static func newWatchOnly(chainId: UInt64, address: String)throws  -> AlloyClient  {
    return try  FfiConverterTypeAlloyClient_lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_walletkit_fn_constructor_alloyclient_new_watch_only(
        FfiConverterUInt64.lower(chainId),
        FfiConverterString.lower(address),$0
    )
})
}
    

    
open func address() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_walletkit_fn_method_alloyclient_address(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func chainId() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_walletkit_fn_method_alloyclient_chain_id(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func derivationPath() -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_walletkit_fn_method_alloyclient_derivation_path(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func isActiveAddress(address: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_walletkit_fn_method_alloyclient_is_active_address(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(address),$0
    )
})
}
    
open func isValidAddress(address: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_walletkit_fn_method_alloyclient_is_valid_address(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(address),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAlloyClient: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = AlloyClient

    public static func lift(_ handle: UInt64) throws -> AlloyClient {
        return AlloyClient(unsafeFromHandle: handle)
    }

    public static func lower(_ value: AlloyClient) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AlloyClient {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: AlloyClient, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlloyClient_lift(_ handle: UInt64) throws -> AlloyClient {
    return try FfiConverterTypeAlloyClient.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlloyClient_lower(_ value: AlloyClient) -> UInt64 {
    return FfiConverterTypeAlloyClient.lower(value)
}






public protocol MnemonicProtocol: AnyObject, Sendable {
    
    func entropy()  -> [UInt8]
    
    func seedPhrase()  -> String
    
}
open class Mnemonic: MnemonicProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_walletkit_fn_clone_mnemonic(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_walletkit_fn_free_mnemonic(handle, $0) }
    }

    
public static func fromEntropy(entropy: [UInt8])throws  -> Mnemonic  {
    return try  FfiConverterTypeMnemonic_lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_walletkit_fn_constructor_mnemonic_from_entropy(
        FfiConverterSequenceUInt8.lower(entropy),$0
    )
})
}
    
public static func fromSeedPhrase(seedPhrase: String)throws  -> Mnemonic  {
    return try  FfiConverterTypeMnemonic_lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_walletkit_fn_constructor_mnemonic_from_seed_phrase(
        FfiConverterString.lower(seedPhrase),$0
    )
})
}
    

    
open func entropy() -> [UInt8]  {
    return try!  FfiConverterSequenceUInt8.lift(try! rustCall() {
    uniffi_walletkit_fn_method_mnemonic_entropy(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func seedPhrase() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_walletkit_fn_method_mnemonic_seed_phrase(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMnemonic: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Mnemonic

    public static func lift(_ handle: UInt64) throws -> Mnemonic {
        return Mnemonic(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Mnemonic) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Mnemonic {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Mnemonic, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMnemonic_lift(_ handle: UInt64) throws -> Mnemonic {
    return try FfiConverterTypeMnemonic.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMnemonic_lower(_ value: Mnemonic) -> UInt64 {
    return FfiConverterTypeMnemonic.lower(value)
}






public protocol SuiClientProtocol: AnyObject, Sendable {
    
    func address()  -> String
    
    func derivationPath()  -> String?
    
    func isActiveAddress(address: String)  -> Bool
    
    func isValidAddress(address: String)  -> Bool
    
}
open class SuiClient: SuiClientProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_walletkit_fn_clone_suiclient(self.handle, $0) }
    }
public convenience init(accountIndex: UInt64, keyScheme: SignatureScheme, privateKey: [UInt8], password: String?, rpcUrl: String)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_walletkit_fn_constructor_suiclient_new(
        FfiConverterUInt64.lower(accountIndex),
        FfiConverterTypeSignatureScheme_lower(keyScheme),
        FfiConverterSequenceUInt8.lower(privateKey),
        FfiConverterOptionString.lower(password),
        FfiConverterString.lower(rpcUrl),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_walletkit_fn_free_suiclient(handle, $0) }
    }

    
public static func newWatchOnly(address: String, rpcUrl: String)throws  -> SuiClient  {
    return try  FfiConverterTypeSuiClient_lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_walletkit_fn_constructor_suiclient_new_watch_only(
        FfiConverterString.lower(address),
        FfiConverterString.lower(rpcUrl),$0
    )
})
}
    

    
open func address() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_walletkit_fn_method_suiclient_address(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func derivationPath() -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_walletkit_fn_method_suiclient_derivation_path(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func isActiveAddress(address: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_walletkit_fn_method_suiclient_is_active_address(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(address),$0
    )
})
}
    
open func isValidAddress(address: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_walletkit_fn_method_suiclient_is_valid_address(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(address),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSuiClient: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SuiClient

    public static func lift(_ handle: UInt64) throws -> SuiClient {
        return SuiClient(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SuiClient) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SuiClient {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SuiClient, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSuiClient_lift(_ handle: UInt64) throws -> SuiClient {
    return try FfiConverterTypeSuiClient.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSuiClient_lower(_ value: SuiClient) -> UInt64 {
    return FfiConverterTypeSuiClient.lower(value)
}




public enum Error: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case AlloyError(description: String
    )
    case MnemonicError(description: String
    )
    case NotImplemented
    case SuiError(description: String
    )

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension Error: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeError: FfiConverterRustBuffer {
    typealias SwiftType = Error

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Error {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .AlloyError(
            description: try FfiConverterString.read(from: &buf)
            )
        case 2: return .MnemonicError(
            description: try FfiConverterString.read(from: &buf)
            )
        case 3: return .NotImplemented
        case 4: return .SuiError(
            description: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Error, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .AlloyError(description):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(description, into: &buf)
            
        
        case let .MnemonicError(description):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(description, into: &buf)
            
        
        case .NotImplemented:
            writeInt(&buf, Int32(3))
        
        
        case let .SuiError(description):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(description, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeError_lift(_ buf: RustBuffer) throws -> Error {
    return try FfiConverterTypeError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeError_lower(_ value: Error) -> RustBuffer {
    return FfiConverterTypeError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SignatureScheme: Equatable, Hashable {
    
    case bls12381
    case ed25519
    case multiSig
    case secp256k1
    case secp256r1
    case zkLoginAuthenticator
    case passkeyAuthenticator



}

#if compiler(>=6)
extension SignatureScheme: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSignatureScheme: FfiConverterRustBuffer {
    typealias SwiftType = SignatureScheme

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignatureScheme {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .bls12381
        
        case 2: return .ed25519
        
        case 3: return .multiSig
        
        case 4: return .secp256k1
        
        case 5: return .secp256r1
        
        case 6: return .zkLoginAuthenticator
        
        case 7: return .passkeyAuthenticator
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SignatureScheme, into buf: inout [UInt8]) {
        switch value {
        
        
        case .bls12381:
            writeInt(&buf, Int32(1))
        
        
        case .ed25519:
            writeInt(&buf, Int32(2))
        
        
        case .multiSig:
            writeInt(&buf, Int32(3))
        
        
        case .secp256k1:
            writeInt(&buf, Int32(4))
        
        
        case .secp256r1:
            writeInt(&buf, Int32(5))
        
        
        case .zkLoginAuthenticator:
            writeInt(&buf, Int32(6))
        
        
        case .passkeyAuthenticator:
            writeInt(&buf, Int32(7))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignatureScheme_lift(_ buf: RustBuffer) throws -> SignatureScheme {
    return try FfiConverterTypeSignatureScheme.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignatureScheme_lower(_ value: SignatureScheme) -> RustBuffer {
    return FfiConverterTypeSignatureScheme.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]

    public static func write(_ value: [UInt8], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt8.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt8] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt8]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt8.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureWalletkitInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_walletkit_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_walletkit_checksum_method_alloyclient_address() != 46143) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_alloyclient_chain_id() != 47942) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_alloyclient_derivation_path() != 18955) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_alloyclient_is_active_address() != 39577) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_alloyclient_is_valid_address() != 37574) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_mnemonic_entropy() != 64336) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_mnemonic_seed_phrase() != 54900) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_suiclient_address() != 50566) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_suiclient_derivation_path() != 3240) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_suiclient_is_active_address() != 54542) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_suiclient_is_valid_address() != 37941) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_constructor_alloyclient_new() != 34606) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_constructor_alloyclient_new_trezor() != 7789) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_constructor_alloyclient_new_watch_only() != 54464) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_constructor_mnemonic_from_entropy() != 50546) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_constructor_mnemonic_from_seed_phrase() != 17425) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_constructor_suiclient_new() != 16452) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_constructor_suiclient_new_watch_only() != 19123) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureWalletkitInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all