// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(WalletKitFFI)
import WalletKitFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_walletkit_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_walletkit_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureWalletkitInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol AlloyClientProtocol: AnyObject, Sendable {
    
    func address()  -> EthereumAddress
    
    func chainId()  -> UInt64
    
    func erc20(contractAddress: EthereumAddress)  -> Erc20
    
    func estimateFees() async throws  -> [UInt8]
    
    func estimateGas(tx: [UInt8]) async throws  -> UInt64
    
    func getBalance() async throws  -> String
    
    func getNonce() async throws  -> UInt64
    
    func rpcUrl()  -> String
    
    func send(txEnvelope: [UInt8]) async throws  -> String
    
    func txRequest(to: EthereumAddress, amount: String, nonce: UInt64?, gasLimit: UInt64?, fees: [UInt8]?) async throws  -> [UInt8]
    
}
open class AlloyClient: AlloyClientProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_walletkit_fn_clone_alloyclient(self.handle, $0) }
    }
public convenience init(address: EthereumAddress, chainId: UInt64, rpcUrl: String)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_walletkit_fn_constructor_alloyclient_new(
        FfiConverterTypeEthereumAddress_lower(address),
        FfiConverterUInt64.lower(chainId),
        FfiConverterString.lower(rpcUrl),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_walletkit_fn_free_alloyclient(handle, $0) }
    }

    

    
open func address() -> EthereumAddress  {
    return try!  FfiConverterTypeEthereumAddress_lift(try! rustCall() {
    uniffi_walletkit_fn_method_alloyclient_address(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func chainId() -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_walletkit_fn_method_alloyclient_chain_id(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func erc20(contractAddress: EthereumAddress) -> Erc20  {
    return try!  FfiConverterTypeERC20_lift(try! rustCall() {
    uniffi_walletkit_fn_method_alloyclient_erc20(
            self.uniffiCloneHandle(),
        FfiConverterTypeEthereumAddress_lower(contractAddress),$0
    )
})
}
    
open func estimateFees()async throws  -> [UInt8]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_method_alloyclient_estimate_fees(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_rust_buffer,
            completeFunc: ffi_walletkit_rust_future_complete_rust_buffer,
            freeFunc: ffi_walletkit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceUInt8.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func estimateGas(tx: [UInt8])async throws  -> UInt64  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_method_alloyclient_estimate_gas(
                    self.uniffiCloneHandle(),
                    FfiConverterSequenceUInt8.lower(tx)
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_u64,
            completeFunc: ffi_walletkit_rust_future_complete_u64,
            freeFunc: ffi_walletkit_rust_future_free_u64,
            liftFunc: FfiConverterUInt64.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func getBalance()async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_method_alloyclient_get_balance(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_rust_buffer,
            completeFunc: ffi_walletkit_rust_future_complete_rust_buffer,
            freeFunc: ffi_walletkit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func getNonce()async throws  -> UInt64  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_method_alloyclient_get_nonce(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_u64,
            completeFunc: ffi_walletkit_rust_future_complete_u64,
            freeFunc: ffi_walletkit_rust_future_free_u64,
            liftFunc: FfiConverterUInt64.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func rpcUrl() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_walletkit_fn_method_alloyclient_rpc_url(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func send(txEnvelope: [UInt8])async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_method_alloyclient_send(
                    self.uniffiCloneHandle(),
                    FfiConverterSequenceUInt8.lower(txEnvelope)
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_rust_buffer,
            completeFunc: ffi_walletkit_rust_future_complete_rust_buffer,
            freeFunc: ffi_walletkit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func txRequest(to: EthereumAddress, amount: String, nonce: UInt64?, gasLimit: UInt64?, fees: [UInt8]?)async throws  -> [UInt8]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_method_alloyclient_tx_request(
                    self.uniffiCloneHandle(),
                    FfiConverterTypeEthereumAddress_lower(to),FfiConverterString.lower(amount),FfiConverterOptionUInt64.lower(nonce),FfiConverterOptionUInt64.lower(gasLimit),FfiConverterOptionSequenceUInt8.lower(fees)
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_rust_buffer,
            completeFunc: ffi_walletkit_rust_future_complete_rust_buffer,
            freeFunc: ffi_walletkit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceUInt8.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAlloyClient: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = AlloyClient

    public static func lift(_ handle: UInt64) throws -> AlloyClient {
        return AlloyClient(unsafeFromHandle: handle)
    }

    public static func lower(_ value: AlloyClient) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AlloyClient {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: AlloyClient, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlloyClient_lift(_ handle: UInt64) throws -> AlloyClient {
    return try FfiConverterTypeAlloyClient.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlloyClient_lower(_ value: AlloyClient) -> UInt64 {
    return FfiConverterTypeAlloyClient.lower(value)
}






public protocol AlloyWalletProtocol: AnyObject, Sendable {
    
    func address()  -> EthereumAddress
    
    func derivationPath()  -> String
    
    func sign(txRequest: [UInt8]) async throws  -> [UInt8]
    
}
open class AlloyWallet: AlloyWalletProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_walletkit_fn_clone_alloywallet(self.handle, $0) }
    }
public convenience init(accountIndex: UInt64, privateKey: [UInt8])throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_walletkit_fn_constructor_alloywallet_new(
        FfiConverterUInt64.lower(accountIndex),
        FfiConverterSequenceUInt8.lower(privateKey),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_walletkit_fn_free_alloywallet(handle, $0) }
    }

    
public static func newTrezor(accountIndex: UInt64, chainId: UInt64?)async throws  -> AlloyWallet  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_constructor_alloywallet_new_trezor(FfiConverterUInt64.lower(accountIndex),FfiConverterOptionUInt64.lower(chainId)
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_u64,
            completeFunc: ffi_walletkit_rust_future_complete_u64,
            freeFunc: ffi_walletkit_rust_future_free_u64,
            liftFunc: FfiConverterTypeAlloyWallet_lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    

    
open func address() -> EthereumAddress  {
    return try!  FfiConverterTypeEthereumAddress_lift(try! rustCall() {
    uniffi_walletkit_fn_method_alloywallet_address(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func derivationPath() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_walletkit_fn_method_alloywallet_derivation_path(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func sign(txRequest: [UInt8])async throws  -> [UInt8]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_method_alloywallet_sign(
                    self.uniffiCloneHandle(),
                    FfiConverterSequenceUInt8.lower(txRequest)
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_rust_buffer,
            completeFunc: ffi_walletkit_rust_future_complete_rust_buffer,
            freeFunc: ffi_walletkit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceUInt8.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAlloyWallet: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = AlloyWallet

    public static func lift(_ handle: UInt64) throws -> AlloyWallet {
        return AlloyWallet(unsafeFromHandle: handle)
    }

    public static func lower(_ value: AlloyWallet) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AlloyWallet {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: AlloyWallet, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlloyWallet_lift(_ handle: UInt64) throws -> AlloyWallet {
    return try FfiConverterTypeAlloyWallet.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAlloyWallet_lower(_ value: AlloyWallet) -> UInt64 {
    return FfiConverterTypeAlloyWallet.lower(value)
}






public protocol Erc20Protocol: AnyObject, Sendable {
    
    func balanceOf(owner: EthereumAddress) async throws  -> String
    
    func contractAddress()  -> EthereumAddress
    
    func decimals() async throws  -> UInt8
    
    func makeTransferFromTx(from: EthereumAddress, to: EthereumAddress, amount: String) throws  -> [UInt8]
    
    func makeTransferTx(to: EthereumAddress, amount: String, nonce: UInt64?, gasLimit: UInt64?, fees: [UInt8]?) throws  -> [UInt8]
    
    func symbol() async throws  -> String
    
}
open class Erc20: Erc20Protocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_walletkit_fn_clone_erc20(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_walletkit_fn_free_erc20(handle, $0) }
    }

    

    
open func balanceOf(owner: EthereumAddress)async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_method_erc20_balance_of(
                    self.uniffiCloneHandle(),
                    FfiConverterTypeEthereumAddress_lower(owner)
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_rust_buffer,
            completeFunc: ffi_walletkit_rust_future_complete_rust_buffer,
            freeFunc: ffi_walletkit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func contractAddress() -> EthereumAddress  {
    return try!  FfiConverterTypeEthereumAddress_lift(try! rustCall() {
    uniffi_walletkit_fn_method_erc20_contract_address(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func decimals()async throws  -> UInt8  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_method_erc20_decimals(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_u8,
            completeFunc: ffi_walletkit_rust_future_complete_u8,
            freeFunc: ffi_walletkit_rust_future_free_u8,
            liftFunc: FfiConverterUInt8.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func makeTransferFromTx(from: EthereumAddress, to: EthereumAddress, amount: String)throws  -> [UInt8]  {
    return try  FfiConverterSequenceUInt8.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_walletkit_fn_method_erc20_make_transfer_from_tx(
            self.uniffiCloneHandle(),
        FfiConverterTypeEthereumAddress_lower(from),
        FfiConverterTypeEthereumAddress_lower(to),
        FfiConverterString.lower(amount),$0
    )
})
}
    
open func makeTransferTx(to: EthereumAddress, amount: String, nonce: UInt64?, gasLimit: UInt64?, fees: [UInt8]?)throws  -> [UInt8]  {
    return try  FfiConverterSequenceUInt8.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_walletkit_fn_method_erc20_make_transfer_tx(
            self.uniffiCloneHandle(),
        FfiConverterTypeEthereumAddress_lower(to),
        FfiConverterString.lower(amount),
        FfiConverterOptionUInt64.lower(nonce),
        FfiConverterOptionUInt64.lower(gasLimit),
        FfiConverterOptionSequenceUInt8.lower(fees),$0
    )
})
}
    
open func symbol()async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_method_erc20_symbol(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_rust_buffer,
            completeFunc: ffi_walletkit_rust_future_complete_rust_buffer,
            freeFunc: ffi_walletkit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeERC20: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Erc20

    public static func lift(_ handle: UInt64) throws -> Erc20 {
        return Erc20(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Erc20) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Erc20 {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Erc20, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeERC20_lift(_ handle: UInt64) throws -> Erc20 {
    return try FfiConverterTypeERC20.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeERC20_lower(_ value: Erc20) -> UInt64 {
    return FfiConverterTypeERC20.lower(value)
}






public protocol EthereumAddressProtocol: AnyObject, Sendable {
    
    func toString()  -> String
    
}
open class EthereumAddress: EthereumAddressProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_walletkit_fn_clone_ethereumaddress(self.handle, $0) }
    }
public convenience init(string: String)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_walletkit_fn_constructor_ethereumaddress_new(
        FfiConverterString.lower(string),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_walletkit_fn_free_ethereumaddress(handle, $0) }
    }

    

    
open func toString() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_walletkit_fn_method_ethereumaddress_to_string(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEthereumAddress: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = EthereumAddress

    public static func lift(_ handle: UInt64) throws -> EthereumAddress {
        return EthereumAddress(unsafeFromHandle: handle)
    }

    public static func lower(_ value: EthereumAddress) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EthereumAddress {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: EthereumAddress, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEthereumAddress_lift(_ handle: UInt64) throws -> EthereumAddress {
    return try FfiConverterTypeEthereumAddress.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEthereumAddress_lower(_ value: EthereumAddress) -> UInt64 {
    return FfiConverterTypeEthereumAddress.lower(value)
}






public protocol MnemonicProtocol: AnyObject, Sendable {
    
    func entropy()  -> [UInt8]
    
    func seedPhrase()  -> String
    
}
open class Mnemonic: MnemonicProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_walletkit_fn_clone_mnemonic(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        try! rustCall { uniffi_walletkit_fn_free_mnemonic(handle, $0) }
    }

    
public static func fromEntropy(entropy: [UInt8])throws  -> Mnemonic  {
    return try  FfiConverterTypeMnemonic_lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_walletkit_fn_constructor_mnemonic_from_entropy(
        FfiConverterSequenceUInt8.lower(entropy),$0
    )
})
}
    
public static func fromSeedPhrase(seedPhrase: String)throws  -> Mnemonic  {
    return try  FfiConverterTypeMnemonic_lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_walletkit_fn_constructor_mnemonic_from_seed_phrase(
        FfiConverterString.lower(seedPhrase),$0
    )
})
}
    

    
open func entropy() -> [UInt8]  {
    return try!  FfiConverterSequenceUInt8.lift(try! rustCall() {
    uniffi_walletkit_fn_method_mnemonic_entropy(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func seedPhrase() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_walletkit_fn_method_mnemonic_seed_phrase(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMnemonic: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Mnemonic

    public static func lift(_ handle: UInt64) throws -> Mnemonic {
        return Mnemonic(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Mnemonic) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Mnemonic {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Mnemonic, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMnemonic_lift(_ handle: UInt64) throws -> Mnemonic {
    return try FfiConverterTypeMnemonic.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMnemonic_lower(_ value: Mnemonic) -> UInt64 {
    return FfiConverterTypeMnemonic.lower(value)
}






public protocol SuiAddressProtocol: AnyObject, Sendable {
    
    func toString()  -> String
    
}
open class SuiAddress: SuiAddressProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_walletkit_fn_clone_suiaddress(self.handle, $0) }
    }
public convenience init(string: String)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_walletkit_fn_constructor_suiaddress_new(
        FfiConverterString.lower(string),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_walletkit_fn_free_suiaddress(handle, $0) }
    }

    

    
open func toString() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_walletkit_fn_method_suiaddress_to_string(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSuiAddress: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SuiAddress

    public static func lift(_ handle: UInt64) throws -> SuiAddress {
        return SuiAddress(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SuiAddress) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SuiAddress {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SuiAddress, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSuiAddress_lift(_ handle: UInt64) throws -> SuiAddress {
    return try FfiConverterTypeSuiAddress.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSuiAddress_lower(_ value: SuiAddress) -> UInt64 {
    return FfiConverterTypeSuiAddress.lower(value)
}






public protocol SuiClientProtocol: AnyObject, Sendable {
    
    func address()  -> SuiAddress
    
    func getAllBalances(owner: SuiAddress) async throws  -> [UInt8]
    
    func getBalance(coinType: String?) async throws  -> String
    
    func getCoinMetadata(coinType: String) async throws  -> SuiCoinMetadata?
    
    func getReferenceGasPrice() async throws  -> UInt64
    
    func send(txData: [UInt8], signature: [UInt8]) async throws  -> String
    
    func txData(coinType: String, to: SuiAddress, amount: UInt64, gasBudget: UInt64, gasPrice: UInt64) async throws  -> [UInt8]
    
}
open class SuiClient: SuiClientProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_walletkit_fn_clone_suiclient(self.handle, $0) }
    }
public convenience init(address: SuiAddress, rpcUrl: String)async throws  {
    let handle =
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_constructor_suiclient_new(FfiConverterTypeSuiAddress_lower(address),FfiConverterString.lower(rpcUrl)
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_u64,
            completeFunc: ffi_walletkit_rust_future_complete_u64,
            freeFunc: ffi_walletkit_rust_future_free_u64,
            liftFunc: FfiConverterTypeSuiClient_lift,
            errorHandler: FfiConverterTypeError_lift
        )
        
        .uniffiCloneHandle()
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_walletkit_fn_free_suiclient(handle, $0) }
    }

    

    
open func address() -> SuiAddress  {
    return try!  FfiConverterTypeSuiAddress_lift(try! rustCall() {
    uniffi_walletkit_fn_method_suiclient_address(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func getAllBalances(owner: SuiAddress)async throws  -> [UInt8]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_method_suiclient_get_all_balances(
                    self.uniffiCloneHandle(),
                    FfiConverterTypeSuiAddress_lower(owner)
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_rust_buffer,
            completeFunc: ffi_walletkit_rust_future_complete_rust_buffer,
            freeFunc: ffi_walletkit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceUInt8.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func getBalance(coinType: String?)async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_method_suiclient_get_balance(
                    self.uniffiCloneHandle(),
                    FfiConverterOptionString.lower(coinType)
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_rust_buffer,
            completeFunc: ffi_walletkit_rust_future_complete_rust_buffer,
            freeFunc: ffi_walletkit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func getCoinMetadata(coinType: String)async throws  -> SuiCoinMetadata?  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_method_suiclient_get_coin_metadata(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(coinType)
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_rust_buffer,
            completeFunc: ffi_walletkit_rust_future_complete_rust_buffer,
            freeFunc: ffi_walletkit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionTypeSuiCoinMetadata.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func getReferenceGasPrice()async throws  -> UInt64  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_method_suiclient_get_reference_gas_price(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_u64,
            completeFunc: ffi_walletkit_rust_future_complete_u64,
            freeFunc: ffi_walletkit_rust_future_free_u64,
            liftFunc: FfiConverterUInt64.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func send(txData: [UInt8], signature: [UInt8])async throws  -> String  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_method_suiclient_send(
                    self.uniffiCloneHandle(),
                    FfiConverterSequenceUInt8.lower(txData),FfiConverterSequenceUInt8.lower(signature)
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_rust_buffer,
            completeFunc: ffi_walletkit_rust_future_complete_rust_buffer,
            freeFunc: ffi_walletkit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterString.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    
open func txData(coinType: String, to: SuiAddress, amount: UInt64, gasBudget: UInt64, gasPrice: UInt64)async throws  -> [UInt8]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_method_suiclient_tx_data(
                    self.uniffiCloneHandle(),
                    FfiConverterString.lower(coinType),FfiConverterTypeSuiAddress_lower(to),FfiConverterUInt64.lower(amount),FfiConverterUInt64.lower(gasBudget),FfiConverterUInt64.lower(gasPrice)
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_rust_buffer,
            completeFunc: ffi_walletkit_rust_future_complete_rust_buffer,
            freeFunc: ffi_walletkit_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceUInt8.lift,
            errorHandler: FfiConverterTypeError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSuiClient: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SuiClient

    public static func lift(_ handle: UInt64) throws -> SuiClient {
        return SuiClient(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SuiClient) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SuiClient {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SuiClient, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSuiClient_lift(_ handle: UInt64) throws -> SuiClient {
    return try FfiConverterTypeSuiClient.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSuiClient_lower(_ value: SuiClient) -> UInt64 {
    return FfiConverterTypeSuiClient.lower(value)
}






public protocol SuiWalletProtocol: AnyObject, Sendable {
    
    func address()  -> SuiAddress
    
    func derivationPath()  -> String
    
    func sign(txData: [UInt8]) throws  -> [UInt8]
    
}
open class SuiWallet: SuiWalletProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_walletkit_fn_clone_suiwallet(self.handle, $0) }
    }
public convenience init(accountIndex: UInt64, keyScheme: SignatureScheme, privateKey: [UInt8])throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_walletkit_fn_constructor_suiwallet_new(
        FfiConverterUInt64.lower(accountIndex),
        FfiConverterTypeSignatureScheme_lower(keyScheme),
        FfiConverterSequenceUInt8.lower(privateKey),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_walletkit_fn_free_suiwallet(handle, $0) }
    }

    

    
open func address() -> SuiAddress  {
    return try!  FfiConverterTypeSuiAddress_lift(try! rustCall() {
    uniffi_walletkit_fn_method_suiwallet_address(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func derivationPath() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_walletkit_fn_method_suiwallet_derivation_path(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func sign(txData: [UInt8])throws  -> [UInt8]  {
    return try  FfiConverterSequenceUInt8.lift(try rustCallWithError(FfiConverterTypeError_lift) {
    uniffi_walletkit_fn_method_suiwallet_sign(
            self.uniffiCloneHandle(),
        FfiConverterSequenceUInt8.lower(txData),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSuiWallet: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = SuiWallet

    public static func lift(_ handle: UInt64) throws -> SuiWallet {
        return SuiWallet(unsafeFromHandle: handle)
    }

    public static func lower(_ value: SuiWallet) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SuiWallet {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: SuiWallet, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSuiWallet_lift(_ handle: UInt64) throws -> SuiWallet {
    return try FfiConverterTypeSuiWallet.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSuiWallet_lower(_ value: SuiWallet) -> UInt64 {
    return FfiConverterTypeSuiWallet.lower(value)
}






public protocol TrezorProtocol: AnyObject, Sendable {
    
    func deviceId()  -> String
    
    func model()  -> String
    
    func revision()  -> String
    
    func vendor()  -> String
    
}
open class Trezor: TrezorProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_walletkit_fn_clone_trezor(self.handle, $0) }
    }
public convenience init()async throws  {
    let handle =
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_walletkit_fn_constructor_trezor_new(
                )
            },
            pollFunc: ffi_walletkit_rust_future_poll_u64,
            completeFunc: ffi_walletkit_rust_future_complete_u64,
            freeFunc: ffi_walletkit_rust_future_free_u64,
            liftFunc: FfiConverterTypeTrezor_lift,
            errorHandler: FfiConverterTypeError_lift
        )
        
        .uniffiCloneHandle()
    self.init(unsafeFromHandle: handle)
}

    deinit {
        try! rustCall { uniffi_walletkit_fn_free_trezor(handle, $0) }
    }

    

    
open func deviceId() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_walletkit_fn_method_trezor_device_id(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func model() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_walletkit_fn_method_trezor_model(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func revision() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_walletkit_fn_method_trezor_revision(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func vendor() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_walletkit_fn_method_trezor_vendor(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTrezor: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Trezor

    public static func lift(_ handle: UInt64) throws -> Trezor {
        return Trezor(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Trezor) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Trezor {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Trezor, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrezor_lift(_ handle: UInt64) throws -> Trezor {
    return try FfiConverterTypeTrezor.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTrezor_lower(_ value: Trezor) -> UInt64 {
    return FfiConverterTypeTrezor.lower(value)
}




public struct SuiCoinMetadata: Equatable, Hashable {
    public var name: String
    public var symbol: String
    public var decimals: UInt8
    public var description: String
    public var iconUrl: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, symbol: String, decimals: UInt8, description: String, iconUrl: String?) {
        self.name = name
        self.symbol = symbol
        self.decimals = decimals
        self.description = description
        self.iconUrl = iconUrl
    }

    
}

#if compiler(>=6)
extension SuiCoinMetadata: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSuiCoinMetadata: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SuiCoinMetadata {
        return
            try SuiCoinMetadata(
                name: FfiConverterString.read(from: &buf), 
                symbol: FfiConverterString.read(from: &buf), 
                decimals: FfiConverterUInt8.read(from: &buf), 
                description: FfiConverterString.read(from: &buf), 
                iconUrl: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: SuiCoinMetadata, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.symbol, into: &buf)
        FfiConverterUInt8.write(value.decimals, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterOptionString.write(value.iconUrl, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSuiCoinMetadata_lift(_ buf: RustBuffer) throws -> SuiCoinMetadata {
    return try FfiConverterTypeSuiCoinMetadata.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSuiCoinMetadata_lower(_ value: SuiCoinMetadata) -> RustBuffer {
    return FfiConverterTypeSuiCoinMetadata.lower(value)
}


public enum Error: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case AlloyError(description: String
    )
    case MnemonicError(description: String
    )
    case InvalidAddress(description: String
    )
    case NotImplemented
    case RuntimeError(description: String
    )
    case SuiError(description: String
    )
    case TrezorError(description: String
    )

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension Error: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeError: FfiConverterRustBuffer {
    typealias SwiftType = Error

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Error {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .AlloyError(
            description: try FfiConverterString.read(from: &buf)
            )
        case 2: return .MnemonicError(
            description: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidAddress(
            description: try FfiConverterString.read(from: &buf)
            )
        case 4: return .NotImplemented
        case 5: return .RuntimeError(
            description: try FfiConverterString.read(from: &buf)
            )
        case 6: return .SuiError(
            description: try FfiConverterString.read(from: &buf)
            )
        case 7: return .TrezorError(
            description: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: Error, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .AlloyError(description):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(description, into: &buf)
            
        
        case let .MnemonicError(description):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(description, into: &buf)
            
        
        case let .InvalidAddress(description):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(description, into: &buf)
            
        
        case .NotImplemented:
            writeInt(&buf, Int32(4))
        
        
        case let .RuntimeError(description):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(description, into: &buf)
            
        
        case let .SuiError(description):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(description, into: &buf)
            
        
        case let .TrezorError(description):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(description, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeError_lift(_ buf: RustBuffer) throws -> Error {
    return try FfiConverterTypeError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeError_lower(_ value: Error) -> RustBuffer {
    return FfiConverterTypeError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SignatureScheme: Equatable, Hashable {
    
    case bls12381
    case ed25519
    case multiSig
    case secp256k1
    case secp256r1
    case zkLoginAuthenticator
    case passkeyAuthenticator



}

#if compiler(>=6)
extension SignatureScheme: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSignatureScheme: FfiConverterRustBuffer {
    typealias SwiftType = SignatureScheme

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SignatureScheme {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .bls12381
        
        case 2: return .ed25519
        
        case 3: return .multiSig
        
        case 4: return .secp256k1
        
        case 5: return .secp256r1
        
        case 6: return .zkLoginAuthenticator
        
        case 7: return .passkeyAuthenticator
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SignatureScheme, into buf: inout [UInt8]) {
        switch value {
        
        
        case .bls12381:
            writeInt(&buf, Int32(1))
        
        
        case .ed25519:
            writeInt(&buf, Int32(2))
        
        
        case .multiSig:
            writeInt(&buf, Int32(3))
        
        
        case .secp256k1:
            writeInt(&buf, Int32(4))
        
        
        case .secp256r1:
            writeInt(&buf, Int32(5))
        
        
        case .zkLoginAuthenticator:
            writeInt(&buf, Int32(6))
        
        
        case .passkeyAuthenticator:
            writeInt(&buf, Int32(7))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignatureScheme_lift(_ buf: RustBuffer) throws -> SignatureScheme {
    return try FfiConverterTypeSignatureScheme.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSignatureScheme_lower(_ value: SignatureScheme) -> RustBuffer {
    return FfiConverterTypeSignatureScheme.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeSuiCoinMetadata: FfiConverterRustBuffer {
    typealias SwiftType = SuiCoinMetadata?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeSuiCoinMetadata.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeSuiCoinMetadata.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterSequenceUInt8.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterSequenceUInt8.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]

    public static func write(_ value: [UInt8], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt8.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt8] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt8]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt8.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureWalletkitInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_walletkit_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_walletkit_checksum_method_alloyclient_address() != 49827) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_alloyclient_chain_id() != 47942) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_alloyclient_erc20() != 14222) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_alloyclient_estimate_fees() != 43402) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_alloyclient_estimate_gas() != 39476) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_alloyclient_get_balance() != 2456) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_alloyclient_get_nonce() != 22716) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_alloyclient_rpc_url() != 38683) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_alloyclient_send() != 31787) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_alloyclient_tx_request() != 13043) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_alloywallet_address() != 22003) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_alloywallet_derivation_path() != 45225) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_alloywallet_sign() != 15573) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_erc20_balance_of() != 34671) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_erc20_contract_address() != 46599) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_erc20_decimals() != 5288) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_erc20_make_transfer_from_tx() != 19790) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_erc20_make_transfer_tx() != 46162) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_erc20_symbol() != 13026) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_ethereumaddress_to_string() != 25497) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_mnemonic_entropy() != 64336) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_mnemonic_seed_phrase() != 54900) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_suiaddress_to_string() != 14688) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_suiclient_address() != 24175) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_suiclient_get_all_balances() != 41908) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_suiclient_get_balance() != 9502) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_suiclient_get_coin_metadata() != 51235) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_suiclient_get_reference_gas_price() != 61683) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_suiclient_send() != 42795) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_suiclient_tx_data() != 39980) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_suiwallet_address() != 59812) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_suiwallet_derivation_path() != 42916) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_suiwallet_sign() != 9700) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_trezor_device_id() != 60832) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_trezor_model() != 41192) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_trezor_revision() != 15083) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_method_trezor_vendor() != 39366) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_constructor_alloyclient_new() != 19919) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_constructor_alloywallet_new() != 18594) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_constructor_alloywallet_new_trezor() != 30069) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_constructor_ethereumaddress_new() != 62343) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_constructor_mnemonic_from_entropy() != 50546) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_constructor_mnemonic_from_seed_phrase() != 17425) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_constructor_suiaddress_new() != 63800) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_constructor_suiclient_new() != 42416) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_constructor_suiwallet_new() != 32825) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_walletkit_checksum_constructor_trezor_new() != 62777) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureWalletkitInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all